[versions]
# Artifact version (source of truth)
artifactVersion = "0.1.1-SNAPSHOT"

# Build dependencies
kotlin = "2.3.10"
serialization = "1.10.0"
kotlinxHtml = "0.12.0"
kotlinxIo = "0.8.2"
kotest = "6.1.3"
dokka = "2.1.0"
tailwind = "0.3.1-SNAPSHOT"
vanniktechMavenPublish = "0.35.0"
ktfmt = "0.25.0"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinxHtml"}
kotlinx-html-jvm = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinxHtml"}
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo"}
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Libraries can be bundled together for easier import
[bundles]
kotlinx-html = ["kotlinx-html", "kotlinx-html-jvm"]

[plugins]
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
tailwind = { id = "com.hyeons-lab.tailwind", version.ref = "tailwind" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
